name: CI

on: [pull_request]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Qt Creator and MinGW
      run: |
        choco install qt-creator -y
        choco install mingw make -y

    - name: Build project
      run: |
        "C:\Program Files\Qt\Tools\QtCreator\bin\qtcreator.exe" -noload Welcome -noload QmlDesigner -noload DeviceMode -noload TestIntegrationMode -noload Profile -noload Help -no-analytics
        qmake HD-Embalagens.pro
        mingw32-make

    - name: Run functional tests
      run: |
        # Comandos para executar seus testes funcionais

    - name: Run unit tests
      run: |
        # Comandos para executar seus testes de unidade
