name: CI

on: [pull_request]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Qt and dependencies
      run: |
        choco install qt5 -y
        choco install mingw make -y

    - name: Build project
      run: |
        qmake -o Makefile YourProject.pro
        mingw32-make

    - name: Run unit tests
      run: |
        mingw32-make run_unit_tests
