name: Build and Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Qt
      run: |
        wget https://download.qt.io/official_releases/online_installers/qt-unified-linux-x64-online.run
        chmod +x qt-unified-linux-x64-online.run
        ./qt-unified-linux-x64-online.run --script /path/to/qt-installer-script.qs

    - name: Build project
      run: |
        qmake -o Makefile HD-Embalagens.pro
        make

    - name: Run unit tests
      run: |
        make run_unit_tests
