name: Build and Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Qt and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qt5-default qtbase5-dev qtdeclarative5-dev qtquickcontrols2-5-dev libqt5sql5 libqt5sql5-sqlite

    - name: Build project
      run: |
        qmake -o Makefile HD-Embalagens.pro
        make

    - name: Run unit tests
      run: |
        make run_unit_tests
