name: Build and Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  - name: Install Qt 5
    run: |
      sudo apt-get update
      sudo apt-get install qt5-default

    - name: Build project
      run: |
        qmake -o Makefile HD-Embalagens.pro
        make

    - name: Run unit tests
      run: |
        make run_unit_tests
